# Module 11 Challenge
## Deliverable 2: Scrape and Analyze Mars Weather Data

In [1]:
# Importing relevant libraries
from splinter import Browser
from bs4 import BeautifulSoup as soup
# import matplotlib.pyplot as plt
import pandas as pd

In [28]:
browser = Browser('chrome')

### Step 1: Visit the Website

Use automated browsing to visit the [Mars Temperature Data Site](https://static.bc-edx.com/data/web/mars_facts/temperature.html). Inspect the page to identify which elements to scrape.

   > **Hint** To identify which elements to scrape, you might want to inspect the page by using Chrome DevTools to discover whether the table contains usable classes.

In [29]:
# Visit the website
# https://static.bc-edx.com/data/web/mars_facts/temperature.html
url = "https://static.bc-edx.com/data/web/mars_facts/temperature.html"
browser.visit(url)

### Step 2: Scrape the Table

Create a Beautiful Soup object and use it to scrape the data in the HTML table.

Note that this can also be achieved by using the Pandas `read_html` function. However, use Beautiful Soup here to continue sharpening your web scraping skills.

In [4]:
# Create a Beautiful Soup Object
html = browser.html
soup = soup(html, 'html.parser')

In [5]:
# Extract all rows of data
table = soup.find_all('tr', class_='data-row')

### Step 3: Store the Data

Assemble the scraped data into a Pandas DataFrame. The columns should have the same headings as the table on the website. Hereâ€™s an explanation of the column headings:

* `id`: the identification number of a single transmission from the Curiosity rover
* `terrestrial_date`: the date on Earth
* `sol`: the number of elapsed sols (Martian days) since Curiosity landed on Mars
* `ls`: the solar longitude
* `month`: the Martian month
* `min_temp`: the minimum temperature, in Celsius, of a single Martian day (sol)
* `pressure`: The atmospheric pressure at Curiosity's location

In [6]:
# Create an empty list
mars_data = []

# Loop through the scraped data to create a list of rows
for row in table:
    row_data = row.find_all('td')
    row = [r.text for r in row_data]
    mars_data.append(row)

In [7]:
mars_data

[['2', '2012-08-16', '10', '155', '6', '-75.0', '739.0'],
 ['13', '2012-08-17', '11', '156', '6', '-76.0', '740.0'],
 ['24', '2012-08-18', '12', '156', '6', '-76.0', '741.0'],
 ['35', '2012-08-19', '13', '157', '6', '-74.0', '732.0'],
 ['46', '2012-08-20', '14', '157', '6', '-74.0', '740.0'],
 ['57', '2012-08-21', '15', '158', '6', '-78.0', '740.0'],
 ['68', '2012-08-22', '16', '158', '6', '-77.0', '740.0'],
 ['79', '2012-08-23', '17', '159', '6', '-76.0', '742.0'],
 ['112', '2012-08-27', '21', '161', '6', '-74.0', '741.0'],
 ['114', '2012-08-28', '22', '162', '6', '-74.0', '742.0'],
 ['123', '2012-08-29', '23', '162', '6', '-75.0', '741.0'],
 ['134', '2012-08-30', '24', '163', '6', '-75.0', '742.0'],
 ['145', '2012-08-31', '25', '163', '6', '-75.0', '743.0'],
 ['156', '2012-09-01', '26', '164', '6', '-76.0', '745.0'],
 ['163', '2012-09-02', '27', '164', '6', '-75.0', '743.0'],
 ['170', '2012-09-03', '28', '165', '6', '-75.0', '745.0'],
 ['171', '2012-09-04', '29', '166', '6', '-75.0', '747.0'],
 ['172', '2012-09-05', '30', '166', '6', '-74.0', '747.0'],
 ['173', '2012-09-06', '31', '167', '6', '-74.0', '745.0'],
 ['175', '2012-09-08', '33', '168', '6', '-73.0', '748.0'],
 ['176', '2012-09-10', '34', '168', '6', '-73.0', '748.0'],
 ['177', '2012-09-11', '35', '169', '6', '-73.0', '749.0'],
 ['178', '2012-09-12', '36', '169', '6', '-73.0', '750.0'],
 ['179', '2012-09-13', '37', '170', '6', '-73.0', '750.0'],
 ['180', '2012-09-14', '38', '171', '6', '-73.0', '750.0'],
 ['181', '2012-09-15', '39', '171', '6', '-75.0', '751.0'],
 ['182', '2012-09-16', '40', '172', '6', '-75.0', '753.0'],
 ['183', '2012-09-17', '41', '172', '6', '-75.0', '753.0'],
 ['184', '2012-09-18', '42', '173', '6', '-75.0', '754.0'],
 ['185', '2012-09-19', '43', '173', '6', '-74.0', '756.0'],
 ['186', '2012-09-20', '44', '174', '6', '-75.0', '757.0'],
 ['187', '2012-09-21', '45', '175', '6', '-74.0', '758.0'],
 ['188', '2012-09-22', '46', '175', '6', '-74.0', '758.0'],
 ['189', '2012-09-23', '47', '176', '6', '-75.0', '758.0'],
 ['190', '2012-09-24', '48', '176', '6', '-75.0', '759.0'],
 ['191', '2012-09-25', '49', '177', '6', '-74.0', '761.0'],
 ['192', '2012-09-26', '50', '177', '6', '-72.0', '761.0'],
 ['193', '2012-09-27', '51', '178', '6', '-76.0', '762.0'],
 ['194', '2012-09-28', '52', '179', '6', '-74.0', '762.0'],
 ['195', '2012-09-29', '53', '179', '6', '-71.0', '764.0'],
 ['196', '2012-09-30', '54', '180', '7', '-72.0', '766.0'],
 ['197', '2012-10-01', '55', '180', '7', '-74.0', '766.0'],
 ['198', '2012-10-02', '56', '181', '7', '-73.0', '768.0'],
 ['199', '2012-10-03', '57', '181', '7', '-73.0', '769.0'],
 ['200', '2012-10-04', '58', '182', '7', '-74.0', '769.0'],
 ['201', '2012-10-05', '59', '183', '7', '-76.0', '771.0'],
 ['202', '2012-10-06', '60', '183', '7', '-75.0', '772.0'],
 ['203', '2012-10-07', '61', '184', '7', '-72.0', '772.0'],
 ['204', '2012-10-08', '62', '184', '7', '-72.0', '774.0'],
 ['205', '2012-10-09', '63', '185', '7', '-73.0', '775.0'],
 ['206', '2012-10-10', '64', '186', '7', '-74.0', '776.0'],
 ['207', '2012-10-11', '65', '186', '7', '-72.0', '777.0'],
 ['208', '2012-10-12', '66', '187', '7', '-73.0', '778.0'],
 ['209', '2012-10-13', '67', '187', '7', '-73.0', '780.0'],
 ['210', '2012-10-14', '68', '188', '7', '-71.0', '781.0'],
 ['211', '2012-10-15', '69', '189', '7', '-73.0', '778.0'],
 ['212', '2012-10-17', '70', '189', '7', '-72.0', '783.0'],
 ['213', '2012-10-18', '71', '190', '7', '-71.0', '784.0'],
 ['214', '2012-10-19', '72', '190', '7', '-73.0', '785.0'],
 ['215', '2012-10-20', '73', '191', '7', '-70.0', '788.0'],
 ['216', '2012-10-21', '74', '192', '7', '-72.0', '790.0'],
 ['217', '2012-10-22', '75', '192', '7', '-73.0', '791.0'],
 ['218', '2012-10-23', '76', '193', '7', '-73.0', '792.0'],
 ['219', '2012-10-24', '77', '193', '7', '-71.0', '792.0'],
 ['220', '2012-10-25', '78', '194', '7', '-71.0', '793.0'],
 ['221', '2012-10-26', '79', '195', '7', '-73.0', '795.0'],
 ['222', '2012-10-27', '80', '195', '7', '-70.0', '796.0'],
 ['223', '2012-10-28', '81', '196', '7', '-72.0', '798.0'],
 ['224', '2012-10-29', '82', '196', '7', '-72.0', '799.0'],
 ['225', '2012-10-30', '83', '197', '7', '-72.0', '801.0'],
 ['226', '2012-10-31', '84', '198', '7', '-70.0', '801.0'],
 ['227', '2012-11-01', '85', '198', '7', '-71.0', '805.0'],
 ['228', '2012-11-02', '86', '199', '7', '-71.0', '808.0'],
 ['229', '2012-11-03', '87', '199', '7', '-70.0', '808.0'],
 ['230', '2012-11-04', '88', '200', '7', '-70.0', '811.0'],
 ['231', '2012-11-05', '89', '201', '7', '-73.0', '813.0'],
 ['233', '2012-11-06', '90', '201', '7', '-71.0', '813.0'],
 ['234', '2012-11-07', '91', '202', '7', '-74.0', '817.0'],
 ['235', '2012-11-08', '92', '202', '7', '-74.0', '820.0'],
 ['236', '2012-11-09', '93', '203', '7', '-72.0', '819.0'],
 ['237', '2012-11-10', '94', '204', '7', '-70.0', '822.0'],
 ['238', '2012-11-11', '95', '204', '7', '-68.0', '822.0'],
 ['239', '2012-11-12', '96', '205', '7', '-71.0', '826.0'],
 ['240', '2012-11-13', '97', '206', '7', '-68.0', '828.0'],
 ['241', '2012-11-14', '98', '206', '7', '-68.0', '828.0'],
 ['242', '2012-11-15', '99', '207', '7', '-68.0', '829.0'],
 ['3', '2012-11-16', '100', '207', '7', '-66.0', '829.0'],
 ['4', '2012-11-17', '101', '208', '7', '-65.0', '830.0'],
 ['5', '2012-11-18', '102', '209', '7', '-67.0', '833.0'],
 ['6', '2012-11-19', '103', '209', '7', '-66.0', '836.0'],
 ['7', '2012-11-20', '104', '210', '8', '-67.0', '838.0'],
 ['8', '2012-11-21', '105', '211', '8', '-66.0', '839.0'],
 ['9', '2012-11-23', '106', '211', '8', '-66.0', '841.0'],
 ['10', '2012-11-24', '107', '212', '8', '-66.0', '844.0'],
 ['11', '2012-11-25', '108', '212', '8', '-65.0', '845.0'],
 ['12', '2012-11-26', '109', '213', '8', '-64.0', '844.0'],
 ['14', '2012-11-27', '110', '214', '8', '-65.0', '848.0'],
 ['15', '2012-11-28', '111', '214', '8', '-66.0', '849.0'],
 ['16', '2012-11-29', '112', '215', '8', '-65.0', '852.0'],
 ['17', '2012-11-30', '113', '216', '8', '-66.0', '857.0'],
 ['18', '2012-12-01', '114', '216', '8', '-69.0', '857.0'],
 ['19', '2012-12-02', '115', '217', '8', '-66.0', '857.0'],
 ['20', '2012-12-03', '116', '217', '8', '-67.0', '859.0'],
 ['21', '2012-12-04', '117', '218', '8', '-66.0', '861.0'],
 ['22', '2012-12-05', '118', '219', '8', '-65.0', '864.0'],
 ['23', '2012-12-06', '119', '219', '8', '-66.0', '866.0'],
 ['25', '2012-12-07', '120', '220', '8', '-67.0', '867.0'],
 ['26', '2012-12-08', '121', '221', '8', '-66.0', '869.0'],
 ['27', '2012-12-09', '122', '221', '8', '-65.0', '869.0'],
 ['28', '2012-12-10', '123', '222', '8', '-66.0', '875.0'],
 ['29', '2012-12-11', '124', '223', '8', '-66.0', '876.0'],
 ['30', '2012-12-12', '125', '223', '8', '-68.0', '880.0'],
 ['31', '2012-12-13', '126', '224', '8', '-66.0', '880.0'],
 ['32', '2012-12-14', '127', '224', '8', '-67.0', '884.0'],
 ['33', '2012-12-15', '128', '225', '8', '-67.0', '883.0'],
 ['34', '2012-12-16', '129', '226', '8', '-65.0', '886.0'],
 ['36', '2012-12-17', '130', '226', '8', '-65.0', '888.0'],
 ['37', '2012-12-18', '131', '227', '8', '-65.0', '889.0'],
 ['38', '2012-12-19', '132', '228', '8', '-65.0', '890.0'],
 ['39', '2012-12-20', '133', '228', '8', '-65.0', '891.0'],
 ['40', '2012-12-21', '134', '229', '8', '-67.0', '893.0'],
 ['41', '2012-12-22', '135', '230', '8', '-65.0', '894.0'],
 ['42', '2012-12-23', '136', '230', '8', '-65.0', '897.0'],
 ['43', '2012-12-24', '137', '231', '8', '-64.0', '896.0'],
 ['44', '2012-12-25', '138', '232', '8', '-65.0', '899.0'],
 ['45', '2012-12-26', '139', '232', '8', '-66.0', '899.0'],
 ['47', '2012-12-27', '140', '233', '8', '-66.0', '903.0'],
 ['48', '2012-12-28', '141', '233', '8', '-64.0', '904.0'],
 ['49', '2012-12-29', '142', '234', '8', '-65.0', '906.0'],
 ['50', '2012-12-31', '143', '235', '8', '-63.0', '908.0'],
 ['51', '2013-01-01', '144', '235', '8', '-64.0', '907.0'],
 ['52', '2013-01-02', '145', '236', '8', '-64.0', '909.0'],
 ['53', '2013-01-03', '146', '237', '8', '-65.0', '908.0'],
 ['54', '2013-01-04', '147', '237', '8', '-65.0', '914.0'],
 ['55', '2013-01-05', '148', '238', '8', '-65.0', '912.0'],
 ['56', '2013-01-06', '149', '239', '8', '-65.0', '914.0'],
 ['58', '2013-01-07', '150', '239', '8', '-64.0', '913.0'],
 ['59', '2013-01-08', '151', '240', '9', '-65.0', '915.0'],
 ['60', '2013-01-09', '152', '241', '9', '-63.0', '914.0'],
 ['61', '2013-01-10', '153', '241', '9', '-65.0', '915.0'],
 ['62', '2013-01-11', '154', '242', '9', '-65.0', '917.0'],
 ['63', '2013-01-12', '155', '243', '9', '-64.0', '917.0'],
 ['64', '2013-01-13', '156', '243', '9', '-65.0', '922.0'],
 ['65', '2013-01-14', '157', '244', '9', '-64.0', '920.0'],
 ['66', '2013-01-15', '158', '245', '9', '-66.0', '922.0'],
 ['67', '2013-01-16', '159', '245', '9', '-65.0', '918.0'],
 ['69', '2013-01-17', '160', '246', '9', '-67.0', '919.0'],
 ['70', '2013-01-18', '161', '246', '9', '-65.0', '919.0'],
 ['71', '2013-01-19', '162', '247', '9', '-65.0', '919.0'],
 ['72', '2013-01-20', '163', '248', '9', '-65.0', '919.0'],
 ['73', '2013-01-21', '164', '248', '9', '-64.0', '919.0'],
 ['74', '2013-01-22', '165', '249', '9', '-65.0', '922.0'],
 ['75', '2013-01-23', '166', '250', '9', '-65.0', '922.0'],
 ['76', '2013-01-24', '167', '250', '9', '-65.0', '920.0'],
 ['77', '2013-01-25', '168', '251', '9', '-66.0', '923.0'],
 ['78', '2013-01-26', '169', '252', '9', '-66.0', '922.0'],
 ['80', '2013-01-27', '170', '252', '9', '-66.0', '925.0'],
 ['81', '2013-01-28', '171', '253', '9', '-67.0', '925.0'],
 ['82', '2013-01-29', '172', '254', '9', '-67.0', '923.0'],
 ['83', '2013-01-30', '173', '254', '9', '-67.0', '920.0'],
 ['84', '2013-01-31', '174', '255', '9', '-67.0', '921.0'],
 ['85', '2013-02-01', '175', '256', '9', '-68.0', '921.0'],
 ['86', '2013-02-02', '176', '256', '9', '-67.0', '920.0'],
 ['87', '2013-02-03', '177', '257', '9', '-66.0', '921.0'],
 ['88', '2013-02-04', '178', '258', '9', '-66.0', '920.0'],
 ['89', '2013-02-06', '179', '258', '9', '-66.0', '920.0'],
 ['91', '2013-02-07', '180', '259', '9', '-67.0', '919.0'],
 ['92', '2013-02-08', '181', '260', '9', '-67.0', '918.0'],
 ['93', '2013-02-09', '182', '260', '9', '-67.0', '921.0'],
 ['94', '2013-02-10', '183', '261', '9', '-67.0', '921.0'],
 ['95', '2013-02-11', '184', '261', '9', '-67.0', '923.0'],
 ['96', '2013-02-12', '185', '262', '9', '-67.0', '923.0'],
 ['97', '2013-02-13', '186', '263', '9', '-66.0', '922.0'],
 ['98', '2013-02-14', '187', '263', '9', '-67.0', '921.0'],
 ['99', '2013-02-15', '188', '264', '9', '-68.0', '920.0'],
 ['100', '2013-02-16', '189', '265', '9', '-68.0', '920.0'],
 ['102', '2013-02-17', '190', '265', '9', '-66.0', '917.0'],
 ['103', '2013-02-18', '191', '266', '9', '-67.0', '921.0'],
 ['106', '2013-02-23', '196', '269', '9', '-66.0', '916.0'],
 ['107', '2013-02-24', '197', '270', '10', '-68.0', '915.0'],
 ['108', '2013-02-25', '198', '271', '10', '-67.0', '914.0'],
 ['109', '2013-02-26', '199', '271', '10', '-66.0', '917.0'],
 ['116', '2013-03-23', '223', '287', '10', '-71.0', '895.0'],
 ['117', '2013-03-24', '224', '287', '10', '-69.0', '894.0'],
 ['118', '2013-03-25', '225', '288', '10', '-71.0', '894.0'],
 ['119', '2013-03-26', '226', '288', '10', '-70.0', '894.0'],
 ['120', '2013-03-27', '227', '289', '10', '-70.0', '892.0'],
 ['121', '2013-03-28', '228', '290', '10', '-71.0', '894.0'],
 ['122', '2013-03-29', '229', '290', '10', '-69.0', '894.0'],
 ['124', '2013-03-30', '230', '291', '10', '-69.0', '888.0'],
 ['125', '2013-03-31', '231', '292', '10', '-71.0', '890.0'],
 ['126', '2013-04-01', '232', '292', '10', '-69.0', '888.0'],
 ['127', '2013-04-02', '233', '293', '10', '-69.0', '889.0'],
 ['128', '2013-04-03', '234', '293', '10', '-69.0', '890.0'],
 ['129', '2013-04-04', '235', '294', '10', '-70.0', '886.0'],
 ['130', '2013-04-05', '236', '295', '10', '-72.0', '886.0'],
 ['131', '2013-04-06', '237', '295', '10', '-71.0', '883.0'],
 ['132', '2013-04-07', '238', '296', '10', '-70.0', '885.0'],
 ['133', '2013-04-08', '239', '297', '10', '-73.0', '885.0'],
 ['135', '2013-04-09', '240', '297', '10', '-70.0', '884.0'],
 ['136', '2013-04-10', '241', '298', '10', '-72.0', '884.0'],
 ['137', '2013-04-11', '242', '298', '10', '-70.0', '881.0'],
 ['138', '2013-04-12', '243', '299', '10', '-71.0', '884.0'],
 ['139', '2013-04-13', '244', '300', '11', '-69.0', '878.0'],
 ['140', '2013-04-14', '245', '300', '11', '-70.0', '879.0'],
 ['141', '2013-04-15', '246', '301', '11', '-73.0', '878.0'],
 ['142', '2013-04-16', '247', '301', '11', '-71.0', '873.0'],
 ['143', '2013-04-17', '248', '302', '11', '-70.0', '877.0'],
 ['144', '2013-04-18', '249', '303', '11', '-69.0', '873.0'],
 ['146', '2013-04-19', '250', '303', '11', '-70.0', '877.0'],
 ['147', '2013-04-20', '251', '304', '11', '-71.0', '876.0'],
 ['148', '2013-04-22', '252', '304', '11', '-71.0', '874.0'],
 ['149', '2013-04-23', '253', '305', '11', '-71.0', '877.0'],
 ['150', '2013-04-24', '254', '306', '11', '-70.0', '871.0'],
 ['151', '2013-04-25', '255', '306', '11', '-69.0', '877.0'],
 ['152', '2013-04-26', '256', '307', '11', '-70.0', '871.0'],
 ['153', '2013-04-27', '257', '308', '11', '-70.0', '871.0'],
 ['154', '2013-04-28', '258', '308', '11', '-71.0', '869.0'],
 ['155', '2013-04-29', '259', '309', '11', '-72.0', '871.0'],
 ['157', '2013-04-30', '260', '309', '11', '-70.0', '875.0'],
 ['158', '2013-05-01', '261', '310', '11', '-70.0', '868.0'],
 ['161', '2013-05-08', '268', '314', '11', '-70.0', '864.0'],
 ['162', '2013-05-09', '269', '315', '11', '-72.0', '866.0'],
 ['164', '2013-05-10', '270', '315', '11', '-67.0', '863.0'],
 ['165', '2013-05-11', '271', '316', '11', '-69.0', '864.0'],
 ['166', '2013-05-12', '272', '316', '11', '-71.0', '864.0'],
 ['167', '2013-05-13', '273', '317', '11', '-70.0', '861.0'],
 ['168', '2013-05-14', '274', '318', '11', '-70.0', '861.0'],
 ['169', '2013-05-15', '275', '318', '11', '-67.0', '860.0'],
 ['244', '2013-05-16', '276', '319', '11', '-69.0', '858.0'],
 ['245', '2013-05-17', '277', '319', '11', '-69.0', '857.0'],
 ['246', '2013-05-18', '278', '320', '11', '-67.0', '855.0'],
 ['247', '2013-05-19', '279', '321', '11', '-68.0', '856.0'],
 ['248', '2013-05-20', '280', '321', '11', '-69.0', '856.0'],
 ['249', '2013-05-21', '281', '322', '11', '-68.0', '855.0'],
 ['250', '2013-05-22', '282', '322', '11', '-72.0', '856.0'],
 ['251', '2013-05-23', '283', '323', '11', '-68.0', '854.0'],
 ['252', '2013-05-24', '284', '323', '11', '-71.0', '854.0'],
 ['253', '2013-05-25', '285', '324', '11', '-70.0', '852.0'],
 ['254', '2013-05-26', '286', '325', '11', '-71.0', '854.0'],
 ['255', '2013-05-27', '287', '325', '11', '-72.0', '856.0'],
 ['256', '2013-05-29', '288', '326', '11', '-69.0', '854.0'],
 ['257', '2013-05-30', '289', '326', '11', '-71.0', '854.0'],
 ['258', '2013-05-31', '290', '327', '11', '-71.0', '853.0'],
 ['259', '2013-06-01', '291', '327', '11', '-70.0', '853.0'],
 ['260', '2013-06-02', '292', '328', '11', '-71.0', '853.0'],
 ['261', '2013-06-03', '293', '329', '11', '-72.0', '850.0'],
 ['262', '2013-06-04', '294', '329', '11', '-72.0', '852.0'],
 ['263', '2013-06-05', '295', '330', '12', '-71.0', '853.0'],
 ['264', '2013-06-06', '296', '330', '12', '-71.0', '850.0'],
 ['265', '2013-06-07', '297', '331', '12', '-72.0', '849.0'],
 ['266', '2013-06-08', '298', '331', '12', '-72.0', '850.0'],
 ['267', '2013-06-09', '299', '332', '12', '-71.0', '849.0'],
 ['286', '2013-06-10', '300', '333', '12', '-72.0', '852.0'],
 ['276', '2013-06-11', '301', '333', '12', '-73.0', '852.0'],
 ['287', '2013-06-12', '302', '334', '12', '-71.0', '850.0'],
 ['283', '2013-06-13', '303', '334', '12', '-71.0', '849.0'],
 ['281', '2013-06-14', '304', '335', '12', '-70.0', '848.0'],
 ['275', '2013-06-15', '305', '335', '12', '-71.0', '847.0'],
 ['280', '2013-06-16', '306', '336', '12', '-71.0', '848.0'],
 ['279', '2013-06-17', '307', '336', '12', '-72.0', '851.0'],
 ['282', '2013-06-18', '308', '337', '12', '-73.0', '850.0'],
 ['284', '2013-06-19', '309', '338', '12', '-72.0', '848.0'],
 ['278', '2013-06-20', '310', '338', '12', '-71.0', '849.0'],
 ['277', '2013-06-21', '311', '339', '12', '-74.0', '846.0'],
 ['285', '2013-06-22', '312', '339', '12', '-71.0', '845.0'],
 ['274', '2013-06-23', '313', '340', '12', '-77.0', '849.0'],
 ['272', '2013-06-24', '314', '340', '12', '-73.0', '848.0'],
 ['273', '2013-06-25', '315', '341', '12', '-74.0', '850.0'],
 ['288', '2013-06-26', '316', '341', '12', '-74.0', '851.0'],
 ['268', '2013-06-27', '317', '342', '12', '-72.0', '849.0'],
 ['270', '2013-06-28', '318', '342', '12', '-74.0', '849.0'],
 ['271', '2013-06-29', '319', '343', '12', '-73.0', '847.0'],
 ['269', '2013-06-30', '320', '344', '12', '-74.0', '846.0'],
 ['289', '2013-07-01', '321', '344', '12', '-75.0', '847.0'],
 ['291', '2013-07-02', '322', '345', '12', '-74.0', '849.0'],
 ['290', '2013-07-03', '323', '345', '12', '-74.0', '847.0'],
 ['292', '2013-07-04', '324', '346', '12', '-75.0', '850.0'],
 ['294', '2013-07-06', '325', '346', '12', '-74.0', '847.0'],
 ['295', '2013-07-07', '326', '347', '12', '-72.0', '848.0'],
 ['296', '2013-07-08', '327', '347', '12', '-74.0', '848.0'],
 ['293', '2013-07-09', '328', '348', '12', '-75.0', '847.0'],
 ['298', '2013-07-10', '329', '348', '12', '-74.0', '847.0'],
 ['297', '2013-07-11', '330', '349', '12', '-75.0', '848.0'],
 ['303', '2013-07-12', '331', '349', '12', '-74.0', '848.0'],
 ['300', '2013-07-13', '332', '350', '12', '-76.0', '849.0'],
 ['299', '2013-07-14', '333', '350', '12', '-75.0', '849.0'],
 ['301', '2013-07-15', '334', '351', '12', '-74.0', '852.0'],
 ['302', '2013-07-16', '335', '352', '12', '-76.0', '852.0'],
 ['305', '2013-07-17', '336', '352', '12', '-76.0', '852.0'],
 ['304', '2013-07-18', '337', '353', '12', '-75.0', '853.0'],
 ['306', '2013-07-19', '338', '353', '12', '-78.0', '848.0'],
 ['308', '2013-07-20', '339', '354', '12', '-76.0', '849.0'],
 ['307', '2013-07-21', '340', '354', '12', '-76.0', '851.0'],
 ['310', '2013-07-22', '341', '355', '12', '-77.0', '852.0'],
 ['309', '2013-07-23', '342', '355', '12', '-76.0', '851.0'],
 ['311', '2013-07-24', '343', '356', '12', '-77.0', '850.0'],
 ['317', '2013-07-25', '344', '356', '12', '-77.0', '851.0'],
 ['312', '2013-07-26', '345', '357', '12', '-77.0', '853.0'],
 ['314', '2013-07-27', '346', '357', '12', '-76.0', '853.0'],
 ['313', '2013-07-28', '347', '358', '12', '-77.0', '851.0'],
 ['315', '2013-07-29', '348', '358', '12', '-74.0', '850.0'],
 ['316', '2013-07-30', '349', '359', '12', '-75.0', '852.0'],
 ['318', '2013-07-31', '350', '359', '12', '-76.0', '853.0'],
 ['320', '2013-08-01', '351', '0', '1', '-75.0', '853.0'],
 ['319', '2013-08-02', '352', '0', '1', '-77.0', '854.0'],
 ['323', '2013-08-03', '353', '1', '1', '-75.0', '855.0'],
 ['322', '2013-08-04', '354', '1', '1', '-75.0', '857.0'],
 ['321', '2013-08-05', '355', '2', '1', '-75.0', '857.0'],
 ['324', '2013-08-06', '356', '2', '1', '-77.0', '856.0'],
 ['325', '2013-08-07', '357', '3', '1', '-76.0', '857.0'],
 ['326', '2013-08-17', '366', '7', '1', '-76.0', '861.0'],
 ['328', '2013-08-18', '367', '8', '1', '-76.0', '862.0'],
 ['330', '2013-08-19', '368', '8', '1', '-77.0', '863.0'],
 ['331', '2013-08-20', '369', '9', '1', '-75.0', '865.0'],
 ['332', '2013-08-21', '370', '9', '1', '-79.0', '865.0'],
 ['333', '2013-08-22', '371', '10', '1', '-77.0', '865.0'],
 ['334', '2013-08-23', '372', '10', '1', '-76.0', '866.0'],
 ['335', '2013-08-24', '373', '11', '1', '-79.0', '866.0'],
 ['337', '2013-08-25', '374', '11', '1', '-79.0', '866.0'],
 ['336', '2013-08-26', '375', '12', '1', '-77.0', '867.0'],
 ['340', '2013-08-27', '376', '12', '1', '-78.0', '870.0'],
 ['338', '2013-08-28', '377', '13', '1', '-78.0', '870.0'],
 ['339', '2013-08-29', '378', '13', '1', '-78.0', '869.0'],
 ['341', '2013-08-30', '379', '14', '1', '-79.0', '870.0'],
 ['343', '2013-08-31', '380', '14', '1', '-79.0', '870.0'],
 ['345', '2013-09-01', '381', '15', '1', '-79.0', '871.0'],
 ['344', '2013-09-02', '382', '15', '1', '-76.0', '872.0'],
 ['342', '2013-09-03', '383', '16', '1', '-77.0', '874.0'],

In [8]:
# Create a Pandas DataFrame by using the list of rows and a list of the column names
mars_df = pd.DataFrame(mars_data)
mars_df.columns = ['id', 'terrestrial_date', 'sol', 'ls', 'month', 'min_temp', 'pressure']

In [9]:
# Confirm DataFrame was created successfully
mars_df

        id terrestrial_date   sol   ls month min_temp pressure
0        2       2012-08-16    10  155     6    -75.0    739.0
1       13       2012-08-17    11  156     6    -76.0    740.0
2       24       2012-08-18    12  156     6    -76.0    741.0
3       35       2012-08-19    13  157     6    -74.0    732.0
4       46       2012-08-20    14  157     6    -74.0    740.0
...    ...              ...   ...  ...   ...      ...      ...
1862  1889       2018-02-23  1973  133     5    -78.0    730.0
1863  1892       2018-02-24  1974  134     5    -77.0    729.0
1864  1894       2018-02-25  1975  134     5    -76.0    729.0
1865  1893       2018-02-26  1976  135     5    -77.0    728.0
1866  1895       2018-02-27  1977  135     5    -77.0    727.0

[1867 rows x 7 columns]

### Step 4: Prepare Data for Analysis

Examine the data types that are currently associated with each column. If necessary, cast (or convert) the data to the appropriate `datetime`, `int`, or `float` data types.

  > **Hint** You can use the Pandas `astype` and `to_datetime` methods to accomplish this task.

In [10]:
# Examine data type of each column
mars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1867 entries, 0 to 1866
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                1867 non-null   object
 1   terrestrial_date  1867 non-null   object
 2   sol               1867 non-null   object
 3   ls                1867 non-null   object
 4   month             1867 non-null   object
 5   min_temp          1867 non-null   object
 6   pressure          1867 non-null   object
dtypes: object(7)
memory usage: 102.2+ KB

In [11]:
# Change data types for data analysis
mars_df['terrestrial_date'] = pd.to_datetime(mars_df['terrestrial_date'])
# mars_df.astype({'min_temp':'float'})
mars_df.month = mars_df.month.astype('int')
mars_df.sol = mars_df.sol.astype('int')
mars_df.min_temp = mars_df.min_temp.astype('float')
mars_df.pressure = mars_df.pressure.astype('float')

In [12]:
# Confirm type changes were successful by examining data types again
mars_df.dtypes

id                          object
terrestrial_date    datetime64[ns]
sol                          int64
ls                          object
month                        int64
min_temp                   float64
pressure                   float64
dtype: object

### Step 5: Analyze the Data

Analyze your dataset by using Pandas functions to answer the following questions:

1. How many months exist on Mars?
2. How many Martian (and not Earth) days worth of data exist in the scraped dataset?
3. What are the coldest and the warmest months on Mars (at the location of Curiosity)? To answer this question:
    * Find the average the minimum daily temperature for all of the months.
    * Plot the results as a bar chart.
4. Which months have the lowest and the highest atmospheric pressure on Mars? To answer this question:
    * Find the average the daily atmospheric pressure of all the months.
    * Plot the results as a bar chart.
5. About how many terrestrial (Earth) days exist in a Martian year? To answer this question:
    * Consider how many days elapse on Earth in the time that Mars circles the Sun once.
    * Visually estimate the result by plotting the daily minimum temperature.

In [13]:
# 1. How many months are there on Mars?
mars_df['month'].nunique()

12

In [14]:
# 2. How many Martian days' worth of data are there?
mars_df['terrestrial_date'].nunique()

1867

In [15]:
# 3. What is the average low temperature by month?
mars_month = mars_df.groupby(["month"])['min_temp'].mean()
mars_month = pd.DataFrame(mars_month)
mars_month.sort_index(ascending=True, inplace=True)
mars_month

        min_temp
month
1     -77.160920
2     -79.932584
3     -83.307292
4     -82.747423
5     -79.308725
6     -75.299320
7     -72.281690
8     -68.382979
9     -69.171642
10    -71.982143
11    -71.985507
12    -74.451807

In [16]:
# Plot the average temperature by month
# mars_month.plot(kind='bar')

# having issues with my environment but I will plot this and resubmit when i can

In [23]:
# Identify the coldest and hottest months in Curiosity's location
mars_month.sort_values(by=['min_temp'])

        min_temp
month
3     -83.307292
4     -82.747423
2     -79.932584
5     -79.308725
1     -77.160920
6     -75.299320
12    -74.451807
7     -72.281690
11    -71.985507
10    -71.982143
9     -69.171642
8     -68.382979

In [18]:
# 4. Average pressure by Martian month
pressure = mars_df.groupby(["month"])['pressure'].mean()
pressure = pd.DataFrame(pressure)
pressure.sort_index(ascending=True, inplace=True)
pressure

         pressure
month
1      862.488506
2      889.455056
3      877.322917
4      806.329897
5      748.557047
6      745.054422
7      795.105634
8      873.829787
9      913.305970
10     887.312500
11     857.014493
12     842.156627

In [19]:
# Plot the average pressure by month
# again, will plot when i can

In [27]:
# 5. How many terrestrial (earth) days are there in a Martian year?
year = mars_df.groupby(mars_df.terrestrial_date.dt.year)['sol'].sum()
year = pd.DataFrame(year)
year

                     sol
terrestrial_date
2012               10162
2013               92800
2014              240335
2015              352577
2016              478834
2017              612376
2018              109172

On average, the third month has the coldest minimum temperature on Mars, and the eighth month is the warmest. But it is always very cold there in human terms!

Atmospheric pressure is, on average, lowest in the sixth month and highest in the ninth.

The distance from peak to peak is roughly 1425-750, or 675 days. A year on Mars appears to be about 675 days from the plot. Internet search confirms that a Mars year is equivalent to 687 earth days.

### Step 6: Save the Data

Export the DataFrame to a CSV file.

In [21]:
# Write the data to a CSV
mars_df.to_csv("mars_dataframe.csv", index=False, header=True)

In [22]:
browser.quit()